# CLASSIFICATION MODEL

In [1]:
# This how i installed openpyxl to read excel
# pip install openpyxl

***1) Loading the excel data***

In [2]:
import pandas as pd

buy_example = pd.read_excel("practice-of-scikit-learn/classification_example.xlsx")
buy_example.head()

,Age,Income,Bought
0,22,25,0
1,25,30,0
2,28,35,0
3,32,40,0
4,35,45,1


***2) Split data to X & y***

In [3]:
from sklearn.model_selection import train_test_split

X = buy_example.drop("Bought", axis=1)
y = buy_example["Bought"]

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y, 
                                                    test_size=0.2,
                                                    random_state=42)

***3) Train a model***

In [4]:
from sklearn.ensemble import RandomForestClassifier

# Creating an instance of the RandomForestClassifier
clf = RandomForestClassifier()

# Train the model 
clf.fit(X_train, y_train)

,"n_estimators n_estimators: int, default=100The number of trees in the forest... versionchanged:: 0.22 The default value of ``n_estimators`` changed from 10 to 100 in 0.22.",100
,"criterion criterion: {""gini"", ""entropy"", ""log_loss""}, default=""gini""The function to measure the quality of a split. Supported criteria are""gini"" for the Gini impurity and ""log_loss"" and ""entropy"" both for theShannon information gain, see :ref:`tree_mathematical_formulation`.Note: This parameter is tree-specific.",'gini'
,"max_depth max_depth: int, default=NoneThe maximum depth of the tree. If None, then nodes are expanded untilall leaves are pure or until all leaves contain less thanmin_samples_split samples.",None
,"min_samples_split min_samples_split: int or float, default=2The minimum number of samples required to split an internal node:- If int, then consider `min_samples_split` as the minimum number.- If float, then `min_samples_split` is a fraction and `ceil(min_samples_split * n_samples)` are the minimum number of samples for each split... versionchanged:: 0.18 Added float values for fractions.",2
,"min_samples_leaf min_samples_leaf: int or float, default=1The minimum number of samples required to be at a leaf node.A split point at any depth will only be considered if it leaves atleast ``min_samples_leaf`` training samples in each of the left andright branches. This may have the effect of smoothing the model,especially in regression.- If int, then consider `min_samples_leaf` as the minimum number.- If float, then `min_samples_leaf` is a fraction and `ceil(min_samples_leaf * n_samples)` are the minimum number of samples for each node... versionchanged:: 0.18 Added float values for fractions.",1
,"min_weight_fraction_leaf min_weight_fraction_leaf: float, default=0.0The minimum weighted fraction of the sum total of weights (of allthe input samples) required to be at a leaf node. Samples haveequal weight when sample_weight is not provided.",0.0
,"max_features max_features: {""sqrt"", ""log2"", None}, int or float, default=""sqrt""The number of features to consider when looking for the best split:- If int, then consider `max_features` features at each split.- If float, then `max_features` is a fraction and `max(1, int(max_features * n_features_in_))` features are considered at each split.- If ""sqrt"", then `max_features=sqrt(n_features)`.- If ""log2"", then `max_features=log2(n_features)`.- If None, then `max_features=n_features`... versionchanged:: 1.1 The default of `max_features` changed from `""auto""` to `""sqrt""`.Note: the search for a split does not stop until at least onevalid partition of the node samples is found, even if it requires toeffectively inspect more than ``max_features`` features.",'sqrt'
,"max_leaf_nodes max_leaf_nodes: int, default=NoneGrow trees with ``max_leaf_nodes`` in best-first fashion.Best nodes are defined as relative reduction in impurity.If None then unlimited number of leaf nodes.",None
,"min_impurity_decrease min_impurity_decrease: float, default=0.0A node will be split if this split induces a decrease of the impuritygreater than or equal to this value.The weighted impurity decrease equation is the following:: N_t / N * (impurity - N_t_R / N_t * right_impurity - N_t_L / N_t * left_impurity)where ``N`` is the total number of samples, ``N_t`` is the number ofsamples at the current node, ``N_t_L`` is the number of samples in theleft child, and ``N_t_R`` is the number of samples in the right child.``N``, ``N_t``, ``N_t_R`` and ``N_t_L`` all refer to the weighted sum,if ``sample_weight`` is passed... versionadded:: 0.19",0.0
,"bootstrap bootstrap: bool, default=TrueWhether bootstrap samples are used when building trees. If False, thewhole dataset is used to build each tree.",True
,"oob_score oob_score: bool or callable, default=FalseWhether to use out-of-bag samples to estimate the generalization score.By default, :func:`~sklearn.metrics.accuracy_score` is used.Provide a callable with signature `metric

***4) Make predictions***

In [5]:
y_preds = clf.predict(X_test)

# EVALUATING THE MODEL

## ***1) Accuracy Score***

In [6]:
y_test

0     0
17    1
15    0
1     0
Name: Bought, dtype: int64

In [7]:
y_preds

array([0, 1, 0, 0])

In [8]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_preds)
print(accuracy)

1.0


## ***2) Confusion Matrix***

In [9]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_preds)

array([[3, 0],
       [0, 1]])

In [10]:
# Using crosstab()
actual_values = pd.crosstab(y_test,
           y_preds,
           rownames=['actual'],
           colnames=['predicted labels'])

actual_values

predicted labels,0,1
actual,,
0,3,0
1,0,1


***Meaning of the crosstab table where the first column i.e `0` is `No` & second column is `1` is `Yes`:***

* ***3 people who were actually `No` were correctly predicted as `No`***
* ***1 person who was actually `Yes was correctly predicted as `Yes`***
* ***0 false +ves(the model never said `Yes` when it was actually `No`)***
* ***0 false -ves(the model never missed a `Yes`)***

## ***3) Classification Report***

In [11]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         3
           1       1.00      1.00      1.00         1

    accuracy                           1.00         4
   macro avg       1.00      1.00      1.00         4
weighted avg       1.00      1.00      1.00         4



### Understanding each metric

1. **Precision**

In [12]:
actual_values

predicted labels,0,1
actual,,
0,3,0
1,0,1


**a) Look at `No` first:**

***The model predicted No exactly 3 times.***

***Were thise predictions correct?***

***Yes***

***All 3 were actually `No`***

***So precision = 3/3 = 1.00***

**b) Now look at `Yes`:**

***The  model predicted `Yes` only `1` time***

***Was it correct?***

***Yes***

***Precision = TP / (TP + FP), TP = true +ve, FP = false +ve***

***So precision = 1/1 = 1.00***

***Meaning: Whenever ur model says `Yes`, it is correct 100% of the time***

2) ***Recall***

***Now ask:***
a) **For `No's`**

***Out of all the actuall `No's`, how many did the model find?***

***There were 3 actual No's, it found all 3***

***So Recall = 3/3 = 1.00***

b) **For `Yes`**

***There was only `1` actual `Yes` and the model found it***

***Recall = TP / TP + FN***

***Recall = 1/1 = 1.00***

***Meaning ur model found every actual `Yes` and every actual `No`***

***It did not miss anything***

3) **F1-score**

***F1 combines `precision` and `Recall`***

**Since**
* ***precision  = 1.00***
* ***Recall = 1.00***

***F1 = 2 * {(Precision * Recall) / (Precision + Recall)}***
  
***Their balance means F1 = 1.00***

***Meaning ur model is perfect on this test data***

4) **Support**

***Support simply counts how many actual examples belong to each class***
* **Actual `No`: 3**
* **Actual `Yes`: 1**

***That is why the support shows:***
* **No   support = 3**
* **Yes  support = 1**

***Support is not a score. It just tells u how many test samples there were in each class***

## ***4) ROC-AUC***

In [13]:
y_probs = clf.predict_proba(X_test)
print(y_probs)

[[1.   0.  ]
 [0.47 0.53]
 [1.   0.  ]
 [1.   0.  ]]


**The left is prob of `No`, right is prob of `Yes` of each matrix**

a) **Step 1: Extract the prob of `Yes`: ROC only needs the prob of the +ve class (`Yes= 1`)**

In [14]:
# So we do:
y_probs = clf.predict_proba(X_test)[:, 1]
print(y_probs)

[0.   0.53 0.   0.  ]


b) **Step 2: Compare with the actual values:**

***From ur previous confusion matrix, i.e:***

In [15]:
actual_values

predicted labels,0,1
actual,,
0,3,0
1,0,1


In [16]:
y_test

0     0
17    1
15    0
1     0
Name: Bought, dtype: int64

In [17]:
compare_values = pd.DataFrame({
    "Actual": y_test,
    "Probability of Yes": y_probs
})

compare_values

,Actual,Probability of Yes
0,0,0.00
17,1,0.53
15,0,0.00
1,0,0.00


**Notice smth important:**
* ***The only `Yes` sample has the highest prob (`0.62`)***
* ***Every `No` sample has a lower prob (`0.00`)***

**That means the model ranked the +ve example above all the -ve examples**

c) **Step 3: Calculate ROC-AUC**

In [18]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, y_probs)

1.0

**Why is ROC 1?**

***ROC-AUC asks:***
* ***Does the model give higher score to +ve examples?***

**Your model gave:**
* ***positve example -> 0.62***
* ***negative examples -> 0.00, 0.00, 0.00***

**Since 0.62 > 0.00 for every comparison, the model perfectly separates the classes**

***There4, ROC-AUC = 1.00***

**Does the prob have to be 1? No**

***This bis a commone misunderstanding***

***Suppose ur probs were:***

In [19]:
pd.DataFrame({
    "Actual": [0, 0, 0, 1],
    "Probability of Yes": [0.10, 0.20, 0.30, 0.40]
})

,Actual,Probability of Yes
0,0,0.1
1,0,0.2
2,0,0.3
3,1,0.4


***The ROC-AUC would still be `1.0`, even tho the highest prob is only `0.40`***

***That's bcos the `+ve` samples still has a higher score than every `-ve` sample***

***ROC-AUC measures the ranking of scores, not how the probs are to `0 `or `1`***

# ***Working under heart disease dataset to create a model***

In [20]:
import pandas as pd
import numpy as np

**1) Importing the data**

In [21]:
heart_disease = pd.read_csv('practice-of-scikit-learn/heart-disease.csv')
heart_disease.head(10)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
5,57,1,0,140,192,0,1,148,0,0.4,1,0,1,1
6,56,0,1,140,294,0,0,153,0,1.3,1,0,2,1
7,44,1,1,120,263,0,1,173,0,0.0,2,0,3,1
8,52,1,2,172,199,1,1,162,0,0.5,2,0,3,1
9,57,1,2,150,168,0,1,174,0,1.6,2,0,2,1


**2) Spliting the data to train and test sets**

In [22]:
from sklearn.model_selection import train_test_split

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size=0.2, random_state=42)

**3) Create an instance of the model to be used and fit it to the training data and scoring on test data:**

***I will be running 5 difft models, so i will import them below and use them:***
* ***RandomForestClassifier()***
* ***LogisticRegression()***
* ***KNeighborsClassifier()***
* ***DecisionTreeClassifier()***
* ***SVC()***
  

### ***A) RandomForestClassifier()***

In [23]:
from sklearn.ensemble import RandomForestClassifier
# from sklearn.linear_model import LogisticRegression
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.svm import SVC

np.random.seed(42)

models_to_use =[
    'from sklearn.ensemble import RandomForestClassifier',
    'from sklearn.linear_model import LogisticRegression',
    'from sklearn.neighbors import KNeighborsClassifier',
    'from sklearn.tree import DecisionTreeClassifier',
    'from sklearn.svm import SVC'
]


# Creating an Instance of Model
clf = RandomForestClassifier()
# clf1 = LogisticRegression()
# clf2 = KNeighborsClassifier()
# clf3 = DecisionTreeClassifier()
# clf4 = SVC(probability=True) # This is so we can use predict_proba() for ROC-AUC

# Fitting the Model
clf.fit(X_train, y_train)

# Scoring the model on test data
clf.score(X_test, y_test)

0.8360655737704918

### **Evaluating the RandomForestClassifier model based on Accuracy, Confusion Matrix, Classification Report and ROC-AUC**

In [24]:
y_test.head()

179    0
228    0
111    1
246    0
60     1
Name: target, dtype: int64

In [25]:
y_preds = clf.predict(X_test)
y_preds

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [26]:
# y_probs = clf.predict_proba(X_test)[:, 1]
# y_probs

### **i) Accuracy**

In [27]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_preds)
print(accuracy)

0.8360655737704918


### **ii) Confusion Matrix**

In [28]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_preds)

array([[24,  5],
       [ 5, 27]])

***From this we identify:***

**(24, 5)**
* **TN (True Negatives) = 24**
* **FP (False Positives) = 5**

**(5, 27)**
* **FN (False Negatives) = 5**
* **TP (True Positives) = 27**

In [29]:
# Using crosstab
comparison = pd.crosstab(y_test,
           y_preds,
           rownames=['actual'],
           colnames=['predicted'])

comparison

predicted,0,1
actual,,
0,24,5
1,5,27


### **iii) Classification report**

In [30]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83        29
           1       0.84      0.84      0.84        32

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61



### **iv) ROC-AUC**

* ***First get the predict_proba() on X_test***

In [31]:
y_probs = clf.predict_proba(X_test)
y_probs[:10]

array([[0.95, 0.05],
       [0.38, 0.62],
       [0.45, 0.55],
       [0.86, 0.14],
       [0.21, 0.79],
       [0.16, 0.84],
       [0.36, 0.64],
       [0.95, 0.05],
       [0.96, 0.04],
       [0.53, 0.47]])

* ***Extract y_probs of the right side***

In [32]:
y_probs = clf.predict_proba(X_test)[:, 1]
y_probs

array([0.05, 0.62, 0.55, 0.14, 0.79, 0.84, 0.64, 0.05, 0.04, 0.47, 0.81,
       0.36, 0.93, 0.13, 0.96, 0.97, 0.99, 0.08, 0.02, 0.06, 0.46, 0.1 ,
       0.65, 0.77, 0.65, 0.66, 0.79, 0.7 , 0.1 , 0.88, 0.09, 0.09, 0.03,
       0.33, 0.53, 0.19, 0.59, 0.78, 0.59, 0.87, 0.81, 0.74, 0.84, 0.66,
       0.71, 0.24, 0.55, 0.99, 0.16, 0.06, 0.35, 0.19, 0.85, 0.66, 0.24,
       0.1 , 0.41, 0.94, 0.14, 0.  , 0.19])

* ***Get the roc_auc_score***

In [33]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, y_probs)

0.9202586206896551

### ***B) LogisticRegression()***

In [34]:
from sklearn.linear_model import LogisticRegression

# Creating an instance of the LogisticRegression model
clf1 = LogisticRegression()

# Fit the training data
clf1.fit(X_train, y_train)

# Score it
clf1.score(X_test, y_test)

C:\Users\HP\Desktop\ml-course-following\sample_project_1\env\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.8852459016393442

### **Evaluating the LogisticRegression model based on Accuracy, Confusion Matrix, Classification Report and ROC-AUC**

In [35]:
y_test.head(10)

179    0
228    0
111    1
246    0
60     1
9      1
119    1
223    0
268    0
33     1
Name: target, dtype: int64

In [36]:
y_preds1 = clf1.predict(X_test)
y_preds1

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0])

### **i) Accuracy**

In [37]:
accuracy1 = accuracy_score(y_test, y_preds1)
print(accuracy1)

0.8852459016393442


### **ii) Confusion Matrix**

In [38]:
confusion_matrix(y_test, y_preds1)

array([[25,  4],
       [ 3, 29]])

In [39]:
# Using crosstab
comparison1 = pd.crosstab(y_test,
           y_preds1,
           rownames=['actual'],
           colnames=['predicted'])

comparison1

predicted,0,1
actual,,
0,25,4
1,3,29


### **iii) Classification report**

In [40]:
print(classification_report(y_test, y_preds1))

              precision    recall  f1-score   support

           0       0.89      0.86      0.88        29
           1       0.88      0.91      0.89        32

    accuracy                           0.89        61
   macro avg       0.89      0.88      0.88        61
weighted avg       0.89      0.89      0.89        61



### **iv) ROC-AUC**

* ***First get the predict_proba() on X_test***

In [41]:
y_probs = clf1.predict_proba(X_test)
y_probs[:10]

array([[0.89557969, 0.10442031],
       [0.24686877, 0.75313123],
       [0.17594705, 0.82405295],
       [0.97422415, 0.02577585],
       [0.06860531, 0.93139469],
       [0.08340913, 0.91659087],
       [0.39444141, 0.60555859],
       [0.9988547 , 0.0011453 ],
       [0.99532805, 0.00467195],
       [0.48401869, 0.51598131]])

* ***Extract y_probs of the right side***

In [42]:
y_probs = clf1.predict_proba(X_test)[:, 1]
y_probs

array([1.04420308e-01, 7.53131232e-01, 8.24052951e-01, 2.57758517e-02,
       9.31394692e-01, 9.16590871e-01, 6.05558594e-01, 1.14529938e-03,
       4.67195479e-03, 5.15981308e-01, 8.03440241e-01, 6.28397576e-02,
       9.30246816e-01, 1.95901578e-02, 9.85896804e-01, 9.53323708e-01,
       9.83144985e-01, 5.05294691e-02, 5.99504077e-03, 1.03393495e-02,
       7.02176847e-01, 7.92803769e-03, 1.23898129e-01, 8.29389927e-01,
       9.28490299e-01, 6.88864940e-01, 8.92584873e-01, 6.83953331e-01,
       6.06475242e-03, 9.20350297e-01, 3.56874379e-02, 2.81217848e-02,
       5.13097541e-03, 7.37048540e-02, 6.90904387e-01, 6.54971003e-02,
       6.40394457e-01, 8.86541319e-01, 8.11470892e-01, 8.62049667e-01,
       5.61390450e-01, 8.35449057e-01, 8.07232011e-01, 6.91268031e-01,
       8.47557717e-01, 5.13612325e-03, 8.17921708e-01, 9.58189683e-01,
       8.31440038e-02, 2.60785924e-02, 5.96033382e-02, 1.11436633e-02,
       8.73171117e-01, 9.80658550e-01, 2.25913506e-01, 7.63005028e-04,
      

* ***Get the roc_auc_score***

In [43]:
roc_auc_score(y_test, y_probs)

0.9234913793103449

In [44]:
models_to_use

['from sklearn.ensemble import RandomForestClassifier',
 'from sklearn.linear_model import LogisticRegression',
 'from sklearn.neighbors import KNeighborsClassifier',
 'from sklearn.tree import DecisionTreeClassifier',
 'from sklearn.svm import SVC']

### C) ***KNeighborsClassifier()***

In [45]:
from sklearn.neighbors import KNeighborsClassifier

# Creating an instance of  KNeighborsClassifier
clf2 =  KNeighborsClassifier()

# Fitting the model to train data
clf2.fit(X_train, y_train)

# Score on test data
clf2.score(X_test, y_test)

0.6885245901639344

### **Evaluating the KNeighborsClassifier model based on Accuracy, Confusion Matrix, Classification Report and ROC-AUC**

In [46]:
y_preds2 = clf2.predict(X_test)
y_preds2

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0])

### **i) Accuracy**

In [47]:
accuracy2 = accuracy_score(y_test, y_preds2)
print(accuracy2)

0.6885245901639344


### **ii) Confusion Matrix**

In [48]:
confusion_matrix(y_test, y_preds2)

array([[18, 11],
       [ 8, 24]])

In [49]:
comparison2 = pd.crosstab(y_test,
                         y_preds2,
                         rownames=["Actual"],
                         colnames=["Predicted"])
comparison2

Predicted,0,1
Actual,,
0,18,11
1,8,24


### **iii) Classification report**

In [50]:
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83        29
           1       0.84      0.84      0.84        32

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61



### **iv) ROC-AUC**

* ***Get the predict_proba()***

In [51]:
y_probs = clf2.predict_proba(X_test)
y_probs[:10]

array([[1. , 0. ],
       [0.2, 0.8],
       [0.2, 0.8],
       [0.2, 0.8],
       [0.8, 0.2],
       [0.4, 0.6],
       [0. , 1. ],
       [0.8, 0.2],
       [1. , 0. ],
       [0.2, 0.8]])

* ***Get only the right side of the predict_proba() values***

In [52]:
y_probs = clf2.predict_proba(X_test)[:, 1]
y_probs

array([0. , 0.8, 0.8, 0.8, 0.2, 0.6, 1. , 0.2, 0. , 0.8, 0.4, 0.4, 0.8,
       0.6, 0.8, 1. , 1. , 0.6, 0.6, 0.2, 0.4, 0. , 0.2, 0.6, 0.6, 1. ,
       0.2, 1. , 0. , 0.6, 0.2, 0.2, 0. , 1. , 0.4, 0.2, 0.8, 0.8, 1. ,
       1. , 0.6, 0.8, 0. , 1. , 0.8, 0.4, 0.6, 0.8, 0.4, 0.8, 0.6, 0.4,
       0.4, 0.6, 0.6, 0.2, 0.2, 0.8, 0.2, 1. , 0.4])

* ***Get the roc_auc_score***

In [53]:
roc_auc_score(y_test, y_probs)

0.7613146551724137

In [54]:
models_to_use

['from sklearn.ensemble import RandomForestClassifier',
 'from sklearn.linear_model import LogisticRegression',
 'from sklearn.neighbors import KNeighborsClassifier',
 'from sklearn.tree import DecisionTreeClassifier',
 'from sklearn.svm import SVC']

### ***D) DecisionTreeClassifier()***

In [55]:
from sklearn.tree import DecisionTreeClassifier

# Instantiating the model
clf3 = DecisionTreeClassifier()

# Fitting the values on the training data
clf3.fit(X_train, y_train)

# Scoring model on the test data
clf3.score(X_test, y_test)

0.8524590163934426

### **Evaluating the DecisionTreeClassifier model based on Accuracy, Confusion Matrix, Classification Report and ROC-AUC**

In [56]:
y_preds3 = clf3.predict(X_test)
y_preds3

array([0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0])

### **i) Accuracy**

In [57]:
accuracy3 = accuracy_score(y_test, y_preds3)
print(accuracy3)

0.8524590163934426


### **ii) Confusion Matrix**

In [58]:
confusion_matrix(y_test, y_preds3)

array([[27,  2],
       [ 7, 25]])

In [59]:
comparison3 = pd.crosstab(y_test,
                         y_preds3,
                         rownames=["Actual"],
                         colnames=["Predicted"])
comparison3

Predicted,0,1
Actual,,
0,27,2
1,7,25


### **iii) Classification Report**

In [60]:
print(classification_report(y_test, y_preds3))

              precision    recall  f1-score   support

           0       0.79      0.93      0.86        29
           1       0.93      0.78      0.85        32

    accuracy                           0.85        61
   macro avg       0.86      0.86      0.85        61
weighted avg       0.86      0.85      0.85        61



### **iv) ROC-AUC**

* ***Get the predict_proba() on X_test***

In [61]:
y_probs = clf3.predict_proba(X_test)
y_probs[:10]

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.]])

* ***Get the right side of the predict_proba() from the matrix i.e the 1 or +ve***

In [62]:
y_probs = y_probs[:, 1]
y_probs

array([0., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1.,
       1., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0.])

* ***Get the roc_auc_score***

In [63]:
roc_auc_score(y_test, y_probs)

0.8561422413793104

In [64]:
models_to_use

['from sklearn.ensemble import RandomForestClassifier',
 'from sklearn.linear_model import LogisticRegression',
 'from sklearn.neighbors import KNeighborsClassifier',
 'from sklearn.tree import DecisionTreeClassifier',
 'from sklearn.svm import SVC']

## ***E) SVC***

In [65]:
from sklearn.svm import SVC

# Instantiating the model
clf4 = SVC(probability=True) # This probability=True is done so we can use predict_proba()
# for ROC_AUC

# Fit model on training data
clf4.fit(X_train, y_train)

# Score model on test data
clf4.score(X_test, y_test)

0.7049180327868853

### **Evaluating the DecisionTreeClassifier model based on Accuracy, Confusion Matrix, Classification Report and ROC-AUC**

In [66]:
y_preds4 = clf4.predict(X_test)
y_preds4

array([0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0])

### **i) Accuracy**

In [67]:
accuracy4 = accuracy_score(y_test, y_preds4)
print(accuracy4)

0.7049180327868853


### **ii) Confusion Matrix**

In [68]:
confusion_matrix(y_test, y_preds4)

array([[15, 14],
       [ 4, 28]])

In [69]:
comparison4 = pd.crosstab(y_test,
                         y_preds4,
                         rownames=["Actual"],
                         colnames=["Predicted"])
comparison4

Predicted,0,1
Actual,,
0,15,14
1,4,28


### **iii) Classification Report**

In [70]:
print(classification_report(y_test, y_preds4))

              precision    recall  f1-score   support

           0       0.79      0.52      0.62        29
           1       0.67      0.88      0.76        32

    accuracy                           0.70        61
   macro avg       0.73      0.70      0.69        61
weighted avg       0.73      0.70      0.69        61



### **iv) ROC-AUC**

* ***Get the predict_proba() on X_test***

In [71]:
y_probs = clf4.predict_proba(X_test)
y_probs[:10]

array([[0.8096196 , 0.1903804 ],
       [0.49207682, 0.50792318],
       [0.26438582, 0.73561418],
       [0.4797908 , 0.5202092 ],
       [0.64386755, 0.35613245],
       [0.27057939, 0.72942061],
       [0.45343997, 0.54656003],
       [0.73591633, 0.26408367],
       [0.75764948, 0.24235052],
       [0.46534487, 0.53465513]])

* ***Get only the right hand side of data i.e `1`***

In [72]:
y_probs = y_probs[:, 1]
y_probs

array([0.1903804 , 0.50792318, 0.73561418, 0.5202092 , 0.35613245,
       0.72942061, 0.54656003, 0.26408367, 0.24235052, 0.53465513,
       0.53895028, 0.38309721, 0.68520954, 0.37456113, 0.76916558,
       0.7644889 , 0.85937012, 0.30609302, 0.2518105 , 0.38230792,
       0.50627277, 0.16399591, 0.08011311, 0.52487492, 0.55929505,
       0.76380189, 0.25802992, 0.77944248, 0.23952224, 0.64062709,
       0.17559754, 0.43202041, 0.15540563, 0.59884247, 0.22222232,
       0.47955404, 0.67339701, 0.73752808, 0.77140284, 0.80673953,
       0.68923027, 0.64538004, 0.46989759, 0.71291532, 0.72980697,
       0.47616546, 0.62121059, 0.80357251, 0.43612709, 0.40552074,
       0.52796276, 0.45843273, 0.42785874, 0.61184251, 0.67063336,
       0.5       , 0.44466233, 0.68096528, 0.45382858, 0.3968424 ,
       0.31725617])

* ***Get to roc_auc_score***

In [73]:
roc_auc_score(y_test, y_probs)

0.8394396551724139

# **Comparing classification and regression**

### Classification---v ----Regression
  
### * **`Accuracy`	 is like      `R² Score`**
### * **`Precision`	 is like      `MAE`**
### * **`Recall`	     is like      `MSE`**
### * **`F1-score`	 is like      `RMSE`**
### * **`ROC-AUC`	     is like      `(No direct equivalent)`**

# **REGRESSION MODEL**

### **So i will be working with these 4**

#### * ***KNeighborsRegressor***
#### * ***RandomForestRegressor***
#### * ***DecisionTreeRegressor***
#### * ***SVR***

In [74]:
models_to_use1 = [
    'from sklearn.ensemble import RandomForestRegressor',
    'from sklearn.linear_model import LinearRegression',
    'from sklearn.neighbors import KNeigborsRegressor',
    'from sklearn.tree import DecisionTreeRegressor'
]

In [75]:
models_to_use1

['from sklearn.ensemble import RandomForestRegressor',
 'from sklearn.linear_model import LinearRegression',
 'from sklearn.neighbors import KNeigborsRegressor',
 'from sklearn.tree import DecisionTreeRegressor']

### **Importing the data**

In [76]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': 

In [77]:
housing["data"]

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]], shape=(20640, 8))

In [78]:
housing["feature_names"]

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [79]:
housing_df = pd.DataFrame(housing['data'], columns=housing["feature_names"])
housing_df.head(10)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25
6,3.6591,52.0,4.931907,0.951362,1094.0,2.128405,37.84,-122.25
7,3.1200,52.0,4.797527,1.061824,1157.0,1.788253,37.84,-122.25
8,2.0804,42.0,4.294118,1.117647,1206.0,2.026891,37.84,-122.26
9,3.6912,52.0,4.970588,0.990196,1551.0,2.172269,37.84,-122.25


In [80]:
housing["target"]

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,))

### ***Adding the `target` as a column to the housing_df***

In [81]:
housing_df["target"] = housing["target"]
housing_df.head(10)

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,target
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
5,4.0368,52.0,4.761658,1.103627,413.0,2.139896,37.85,-122.25,2.697
6,3.6591,52.0,4.931907,0.951362,1094.0,2.128405,37.84,-122.25,2.992
7,3.1200,52.0,4.797527,1.061824,1157.0,1.788253,37.84,-122.25,2.414
8,2.0804,42.0,4.294118,1.117647,1206.0,2.026891,37.84,-122.26,2.267
9,3.6912,52.0,4.970588,0.990196,1551.0,2.172269,37.84,-122.25,2.611


## **A) RandomForestRegression**

In [82]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

np.random.seed(42)

# Splitting the data to X & y
X = housing_df.drop("target", axis=1)
y = housing_df["target"]

# Splitting to training and test data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create an Instance of the RandomForesRegressor Model OR instantiate a model
model = RandomForestRegressor()

# Fit the model to the training data
model.fit(X_train, y_train)

# Score the model on test data
model.score(X_test, y_test)

0.806652667101436

### **Geting our `y_preds`**

In [83]:
y_preds = model.predict(X_test)
y_preds

array([0.4939   , 0.75494  , 4.9285964, ..., 4.8363785, 0.71782  ,
       1.67781  ], shape=(4128,))

### **I will be evaluating these on the:**
* ***R² Score(Coefficient of Determination)***
* ***Mean Absolute Error(MAE)***
* ***Mean Squared Error(MSE)***
* ***Root Mean Squared Error(RMSE)***

### ***i) R² Score***

***This tells u how much of the variation in the target is explained by ur model***

In [84]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_preds)

print(f"The coefficient of determination is {r2 * 100:.2f}%")

The coefficient of determination is 80.67%


***What this means is that, the model explains about 80.67% of the variation in house prices. And this is very good***

### ***ii) Mean Absolute Error(MAE)***

In [85]:
from sklearn.metrics import mean_absolute_error

mae = mean_absolute_error(y_test, y_preds)
mae

0.32656738464147306

***Remeber, the california Housing dataset's target(`MedHousVal`) is measured in `hundreds of thousands of dollars. So 1.0 = $100,000, hence, mae:***

In [86]:
print(f"The Mean Absolute Error is ${mae * 100000:.0f}")

The Mean Absolute Error is $32657


#### ***The above result means our model's prediction is off by about $32,657. For the California Housing dataset, that's a reasonable error***

### **U can also get the `MAE` manually by using `Pandas` & `NumPy` doing:**

* ***Creating a Column for Actual and Predicted values***

In [87]:
df = pd.DataFrame(data={"Actual values": y_test,
                       "Predicted values": y_preds})
df

,Actual values,Predicted values
20046,0.47700,0.493900
3024,0.45800,0.754940
15663,5.00001,4.928596
20484,2.18600,2.540240
9814,2.78000,2.331760
...,...,...
15362,2.63300,2.219830
16623,2.66800,1.947760
18086,5.00001,4.836378
2144,0.72300,0.717820


* ***Getting the diff btw `Predicted and Actual values which is the error(diff)`***

In [88]:
df["error"] = df["Predicted values"] - df["Actual values"]
df

,Actual values,Predicted values,error
20046,0.47700,0.493900,0.016900
3024,0.45800,0.754940,0.296940
15663,5.00001,4.928596,-0.071414
20484,2.18600,2.540240,0.354240
9814,2.78000,2.331760,-0.448240
...,...,...,...
15362,2.63300,2.219830,-0.413170
16623,2.66800,1.947760,-0.720240
18086,5.00001,4.836378,-0.163632
2144,0.72300,0.717820,-0.005180


* ***Getting the Absolute values of the `errors`***

In [89]:
df["abs_error"] = np.abs(df["error"] )
df

,Actual values,Predicted values,error,abs_error
20046,0.47700,0.493900,0.016900,0.016900
3024,0.45800,0.754940,0.296940,0.296940
15663,5.00001,4.928596,-0.071414,0.071414
20484,2.18600,2.540240,0.354240,0.354240
9814,2.78000,2.331760,-0.448240,0.448240
...,...,...,...,...
15362,2.63300,2.219830,-0.413170,0.413170
16623,2.66800,1.947760,-0.720240,0.720240
18086,5.00001,4.836378,-0.163632,0.163632
2144,0.72300,0.717820,-0.005180,0.005180


* ***Getting the mean of the error:***

In [90]:
(df["abs_error"]).mean()

np.float64(0.32656738464147306)

### ***iii) Mean Squared Error(MSE)***

***MSE squares the errors before averaging them***

***MSE mainly helps u compare difft regression models. For example compares, Linear Regression, Decision Tree, Random Forest etc. The Random Forest would be preferred bcos it has the lowest MSE***

***This measures error, but it penalizes large mistakes much more heavily bcos it squares the error***

In [91]:
from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_preds)
mse

0.25336408094921037

### **Also `MSE` can also be gotten this way:**

* ***Square the diff btw Predicted and Actual values:***

In [92]:
df["squared_error"] = np.square(df["error"])
df

,Actual values,Predicted values,error,abs_error,squared_error
20046,0.47700,0.493900,0.016900,0.016900,0.000286
3024,0.45800,0.754940,0.296940,0.296940,0.088173
15663,5.00001,4.928596,-0.071414,0.071414,0.005100
20484,2.18600,2.540240,0.354240,0.354240,0.125486
9814,2.78000,2.331760,-0.448240,0.448240,0.200919
...,...,...,...,...,...
15362,2.63300,2.219830,-0.413170,0.413170,0.170709
16623,2.66800,1.947760,-0.720240,0.720240,0.518746
18086,5.00001,4.836378,-0.163632,0.163632,0.026775
2144,0.72300,0.717820,-0.005180,0.005180,0.000027


* ***Get the mean***

In [93]:
(df["squared_error"]).mean()

np.float64(0.25336408094921037)

### ***iv) Root Mean Squared Error(MSE)***

In [94]:
from sklearn.metrics import root_mean_squared_error

rmse = root_mean_squared_error(y_test, y_preds)
rmse

0.5033528394170538

***RMSE is the square root of MSE, so it's back in the original units of the target.***

***This is also in $100,000s so it will be:***

In [95]:
print(f"The Mean Absolute Error is ${rmse * 100000:.0f}")

The Mean Absolute Error is $50335


***This means the predictions are typically about $50,335 away from the true house price***

***RMSE is larger than MAE bcos it penalizes large prediction errors more heavily***

### **U can also get `RMSE` by doing this:**

***Since `RMSE` is the square root of `MSE`, we can do:***

In [96]:
np.sqrt(mse)

np.float64(0.5033528394170538)

In [97]:
models_to_use1

['from sklearn.ensemble import RandomForestRegressor',
 'from sklearn.linear_model import LinearRegression',
 'from sklearn.neighbors import KNeigborsRegressor',
 'from sklearn.tree import DecisionTreeRegressor']

## **B) LinearRegression**

In [98]:
from sklearn.linear_model import LinearRegression

np.random.seed(42)

# Creating an instance of the model
model1 = LinearRegression()

# Fitting the model to training dataset
model1.fit(X_train, y_train)

# Scoring the model testing dataset
model1.score(X_test, y_test)

0.575787706032451

***Getting the predicted value(y_preds) on X_test***

In [99]:
y_preds1 = model1.predict(X_test)
y_preds1

array([0.71912284, 1.76401657, 2.70965883, ..., 4.46877017, 1.18751119,
       2.00940251], shape=(4128,))

### **Evaluating based on the 4 parameters:**

### ***i)R² Score***

In [100]:
r2 = r2_score(y_test, y_preds1)

print(f"The coefficient of determination is {r2 * 100:.2f}%")

The coefficient of determination is 57.58%


### ***ii) MAE***

In [101]:
mae = mean_absolute_error(y_test, y_preds1)
mae

print(f"The Mean Absolute Error is ${mae * 100000:.0f}")

The Mean Absolute Error is $53320


### ***iii) MSE***

In [102]:
mse = mean_squared_error(y_test, y_preds1)
mse

0.5558915986952442

### ***iv) RMSE***

In [103]:
rmse = root_mean_squared_error(y_test, y_preds1)
rmse

print(f"The Mean Absolute Error is ${rmse * 100000:.0f}")

The Mean Absolute Error is $74558


In [104]:
models_to_use1

['from sklearn.ensemble import RandomForestRegressor',
 'from sklearn.linear_model import LinearRegression',
 'from sklearn.neighbors import KNeigborsRegressor',
 'from sklearn.tree import DecisionTreeRegressor']

## **C) DecisionTreeRegressor**

In [105]:
from sklearn.tree import DecisionTreeRegressor

np.random.seed(42)

# Creating an instance of the model
model2 = DecisionTreeRegressor()

# Fitting the model to the training data
model2.fit(X_train, y_train)

# Scoring on test dataset
model2.score(X_test, y_test)

0.622075845135081

***Get the y_preds on X_test***

In [106]:
y_preds2 = model2.predict(X_test)
y_preds2

array([0.414  , 1.203  , 5.00001, ..., 5.00001, 0.66   , 2.172  ],
      shape=(4128,))

### **Evaluating the model Using the 4 parameters**

## ***i) R² Score***

In [107]:
r2 = r2_score(y_test, y_preds2)

print(f"The coefficient of determination is {r2 * 100:.2f}%")

The coefficient of determination is 62.21%


## ***ii)MAE***

In [108]:
mae = mean_absolute_error(y_test, y_preds2)
mae

print(f"The Mean Absolute Error is ${mae * 100000:.0f}")

The Mean Absolute Error is $45468


## ***iii) MSE***

In [109]:
mse = mean_squared_error(y_test, y_preds2)
mse

0.495235205629094

## ***iv) RMSE***

In [110]:
rmse = root_mean_squared_error(y_test, y_preds2)
rmse

print(f"The Mean Absolute Error is ${rmse * 100000:.0f}")

The Mean Absolute Error is $70373


# **Evaluating A Model With Cross Validation and Scoring Parameter**

***`A point to Note:`***

***THE DIFF BTW OUR `cross_val_score() Evaluation AND regression metrics or classification metrics` IS THAT THE lATTER DEPEND ON ONE TRAIN TEST SPLIT WHILE THE FORMER ARE FOUND ON MULTIPLE TRAIN TEST SPLIT USING CROSS VALIDATION.***

***THE LATTER(`cross val`) TAKES LONGER TO FIND BCOS U HAVE TO TRAIN MULTIPLE MODELS AND EVALUATE THEM. HOWEVER, THEY ARE GENERALLY A BETTER INDICATION OF HOW UR MODEL WILL PERFORM OUTSIDE OF A JUPYTER NOTEBOOK WITH UNSEEN DATA THAN JUST ON ONE SINGLE SPLIT***

## **Cross_Validation:**

***This is spliting our dataset into multiple train and test sets and then evaluating, also training a single model on one particular train and evaluating it on that test set and then repeating that for a number of times: then getting difft scores for each difft split and then we can take the avg. of that to see how our model went across those difft splits***


In [111]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis=1)
y = heart_disease["target"] 

# U can also do this for the other models like DecisionTree, LinearClassification etc
mdl = RandomForestClassifier()

## Cross validation Accuracy

**When scoring=None means that the estimator's default scorer(if available) is used (which is accuracy for classification models).**

In [112]:
np.random.seed(42)
cv_acc = cross_val_score(mdl, X, y, cv=5, scoring=None)
cv_acc

array([0.81967213, 0.90163934, 0.83606557, 0.78333333, 0.78333333])

In [113]:
print(f"The cross-validated accuracy is: {np.mean(cv_acc)*100:.2f}%")

The cross-validated accuracy is: 82.48%


### ***It can also be splitted into any number of parts we want:***

In [114]:
np.random.seed(42)
cv_acc = cross_val_score(mdl, X, y, cv=10, scoring=None)
cv_acc

array([0.80645161, 0.80645161, 0.87096774, 0.9       , 0.9       ,
       0.83333333, 0.73333333, 0.83333333, 0.73333333, 0.76666667])

## ***A) Using the scoring parameter for classification problem: i.e accuracy, precision and recall***

* ***i) Accuracy***

In [115]:
np.random.seed(42)

cv_accuracy = cross_val_score(mdl, X, y, cv=5, scoring="accuracy")
cv_accuracy

array([0.81967213, 0.90163934, 0.83606557, 0.78333333, 0.78333333])

In [116]:
print(f"The cross-validated accuracy is: {np.mean(cv_accuracy)*100:.2f}%")

The cross-validated accuracy is: 82.48%


* ***ii) Precision***

In [117]:
np.random.seed(42)
cv_precision = cross_val_score(clf, X, y, cv=5, scoring="precision")
cv_precision

array([0.82352941, 0.93548387, 0.84848485, 0.79411765, 0.76315789])

In [118]:
print(f"The cross-validated precision is: {np.mean(cv_precision)}")

The cross-validated precision is: 0.8329547346025924


* ***iii) Recall***

In [119]:
np.random.seed(42)
cv_recall = cross_val_score(clf, X, y, cv=5, scoring="recall")
cv_recall

array([0.84848485, 0.87878788, 0.84848485, 0.81818182, 0.87878788])

In [120]:
print(f"The cross-validated recall is: {np.mean(cv_recall)}")

The cross-validated recall is: 0.8545454545454545


* ***iv) F1_score***

In [121]:
np.random.seed(42)
cv_f1 = cross_val_score(clf, X, y, cv=5, scoring="f1")
cv_f1

array([0.8358209 , 0.90625   , 0.84848485, 0.80597015, 0.81690141])

In [122]:
print(f"The cross-validated f1_score is: {np.mean(cv_f1)}")

The cross-validated f1_score is: 0.8426854603423344


* ***v) ROC_AUC***

In [123]:
np.random.seed(42)
cv_roc = cross_val_score(clf, X, y, cv=5, scoring="roc_auc")
cv_roc

array([0.86796537, 0.95995671, 0.89664502, 0.89618406, 0.85409652])

In [124]:
print(f"The cross-validated roc_auc is: {np.mean(cv_roc)}")

The cross-validated roc_auc is: 0.8949695366362033


## ***B) Using the scoring parameter for classification problem: i.e accuracy, precision and recal***

In [125]:
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

X = housing_df.drop("target", axis=1)
y = housing_df["target"]

mdl1 = RandomForestRegressor()

* ***i) R²_Score***

In [126]:
np.random.seed(42)
cv_r2 = cross_val_score(mdl1, X, y, cv=5, scoring="r2") 
# scoring=None is bcos we want to use the default score
cv_r2 

array([0.51688816, 0.70280719, 0.74200859, 0.61659773, 0.68247339])

In [127]:
np.mean(cv_r2)

np.float64(0.6521550148270838)

* ***ii) MSE***

In [128]:
np.random.seed(42)
cv_mse = cross_val_score(mdl1, X, y, cv=5, scoring="neg_mean_squared_error") 
# scoring=None is bcos we want to use the default score
cv_mse 

array([-0.51899364, -0.34788294, -0.37112854, -0.44980156, -0.4626866 ])

In [129]:
np.mean(cv_mse)

np.float64(-0.4300986573544397)

* ***iii) MAE***

In [130]:
np.random.seed(42)
cv_mae = cross_val_score(model, X, y, cv=5, scoring="neg_mean_absolute_error")
np.mean(cv_mae)

np.float64(-0.4662085337112404)

* ***iv) RMSE***

In [131]:
np.random.seed(42)
cv_rmse = cross_val_score(model, X, y, cv=5, scoring="neg_root_mean_squared_error")
np.mean(cv_rmse)

np.float64(-0.6540629062829921)

***NOTE:***

***My advice i.e ChatGpt:***

***Don't replace your current evaluation with cross-validation yet. Keep using the evaluation metrics you've learned. After you're comfortable comparing multiple models, add cross-validation as an extra step to confirm that your chosen model performs consistently across different data splits.***

***You're actually following the same progression that many introductory machine learning courses use, and it's a solid foundation before moving on to more advanced techniques.***

***For e.g:***

***Once you know how to compare models, add cross-validation.***

**Instead of: accuracy_score(y_test, y_preds)**

***U'll also do:***

**cross_val_score(clf, X, y, cv=5, scoring="accuracy").mean()**

***Now u'll have :***
* **Test Accuracy = 0.87**
* **Cross-Validation Accuracy = 0.86**

***If they're close, that's a good sign that ur model generalizes well***

# **Evaluating A Model With Scikit-learn Functions**

### ***This uses `accuracy_score, precision_score, recall_score, f1_score` for `Classification Problems` individually, not combined as seen in classification report***

### ***They are actually the same metrics as the ones gotten from classification reports. It's just that they are returned in dift ways. For e.g:***

#### ***MTHD 1: Individual Metrics***

**from sklearn.metrics import (accuracy_score, precision_score, recall_score, f1_score)**
* **print(accuracy_score(y_test, y_preds))**
* **print(precision_score(y_test, y_preds))**
* **print(recall_score(y_test, y_preds))**
* **print(f1_score(y_test, y_preds))**

#### ***MTHD 2: Classification report***

***from sklearn.metrics import classification_report***
* ***print(classification_report(y_test, y_preds))***
* ***This is gives precision, recall, f1-score, just like the above, but this is combined***

#### **Then why do the individual functions exist?**
***Bcos smts u need one metric jsut like the below:***

**i)**
**precision = precision_score(y_test, y_preds)**

**if precision > 0.90:**
    **print("Excellent model")**

***U can't easily do that directly with the test output of `classification_report()`***

**ii)Another example**

***Suppose you're comparing five models.***

***You could write:***

***results = {
    "Random Forest": accuracy_score(y_test, rf_preds),
    "Decision Tree": accuracy_score(y_test, dt_preds),
    "KNN": accuracy_score(y_test, knn_preds)
}***

**That gives you numbers you can store, compare, or plot.**

***RECOMMENDED: Use both but for the difft situations u find urself as i discussed above***

### ***We also have `r2_score, mean_absolute_error, mean_squared_error` for `Regression Problems`***

### ***1) classification problem:***

In [132]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

np.random.seed(42)

# Create X & y
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]

# Spliting the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create model
clf = RandomForestClassifier()

# Fit model
clf.fit(X_train, y_train)

# Make predictions
y_preds = clf.predict(X_test)

### **Evaluating the model using Evaluation Fcs**

In [133]:
print(f"Classifier metrics on the test set")
print(f"Accuracy: {accuracy_score(y_test, y_preds)*100:.2f}%")
print(f"Precision: {precision_score(y_test, y_preds)}")
print(f"Recall: {recall_score(y_test, y_preds)}")
print(f"F1: {f1_score(y_test, y_preds)}")

Classifier metrics on the test set
Accuracy: 85.25%
Precision: 0.8484848484848485
Recall: 0.875
F1: 0.8615384615384616


### ***2) Regression problem***

In [134]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

np.random.seed(42)

# Create X & y
X = housing_df.drop('target', axis=1)
y = housing_df["target"]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Create model
model = RandomForestRegressor()

# Fit model
model.fit(X_train, y_train)

# Make predictions
y_preds = model.predict(X_test)

# Evaluate model using evaluation fcs
print("Regression metrics on the test set")
print(f"R2 score: {r2_score(y_test, y_preds)}")
print(f"MAE: {mean_absolute_error(y_test, y_preds)}")
print(f"MSE: {mean_squared_error(y_test, y_preds)}")

Regression metrics on the test set
R2 score: 0.806652667101436
MAE: 0.32656738464147306
MSE: 0.25336408094921037
